# Generated by Django 4.2.2 on 2023-06-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_report_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='report',
            name='deadline',
            field=models.DateField(verbose_name='Срок сдачи'),
        ),
        migrations.AlterField(
            model_name='report',
            name='done',
            field=models.BooleanField(verbose_name='Отчет сдан'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(max_length=100, verbose_name='Название отчета'),
        ),
    ]
