# Generated by Django 4.2.2 on 2023-06-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Отчет сдан'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(choices=[('НДС', 'Декларация по НДС'), ('Прибыль', 'Декларация по налогу на прибыль'), ('Взносы', 'Расчет по страховым взносам')], max_length=100, verbose_name='Название отчета'),
        ),
    ]
