# Generated by Django 4.2.2 on 2023-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_report_done_alter_report_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(choices=[('Декларация по НДС', 'НДС'), ('Декларация по налогу на прибыль', 'Прибыль'), ('Расчет по страховым взносам', 'Взносы')], max_length=100, verbose_name='Название отчета'),
        ),
    ]
