# Generated by Django 4.2.2 on 2023-07-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('companies', '0006_alter_report_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuaterPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2023', 2023), ('2024', 2024), ('2025', 2025)], max_length=4)),
                ('period', models.CharField(choices=[('1 QUATER', '1'), ('2 QUATER', '2'), ('3 QUATER', '3'), ('4 QUATER', '4')], max_length=10)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.report')),
            ],
        ),
    ]
