# Generated by Django 4.2.2 on 2023-07-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_report_content_type_quaterperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='companies_r_content_07417e_idx'),
        ),
    ]
