# Generated by Django 4.2.2 on 2023-07-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_report_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quaterperiod',
            name='report_type',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='companies_r_content_07417e_idx',
        ),
        migrations.RemoveField(
            model_name='report',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='QuaterPeriod',
        ),
    ]
