# Generated by Django 4.2.2 on 2023-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_quaterperiod_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='period',
            field=models.CharField(choices=[('Quater', (('1', '1st quater'), ('2', '2nd quater'))), ('Month', (('1', 'jan'), ('2', 'feb')))], default=1, max_length=20, verbose_name='Период отчета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.CharField(choices=[(2023, '2023'), (2024, '2024')], default=1, max_length=20, verbose_name='Год отчета'),
            preserve_default=False,
        ),
    ]
