# Generated by Django 4.2.2 on 2023-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_report_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='period',
            field=models.CharField(choices=[('Quater', (('1st quater', '1st quater'), ('2nd quater', '2nd quater'))), ('Month', (('january', 'jan'), ('february', 'feb')))], max_length=20, verbose_name='Период отчета'),
        ),
    ]
