# Generated by Django 4.2.2 on 2023-07-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_report_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='period',
            field=models.CharField(choices=[('Quater', (('1st quater', '1st quater'), ('2nd quater', '2nd quater'))), ('Month', (('january', 'jan'), ('february', 'feb')))], max_length=100, verbose_name='Период отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024')], max_length=100, verbose_name='Год отчета'),
        ),
    ]
