# Generated by Django 4.2.2 on 2023-07-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_report_period_alter_report_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='period',
            field=models.CharField(choices=[('Quarter', (('1st quarter', '1'), ('2nd quarter', '2'), ('3rd quarter', '3'), ('4th quarter', '4'))), ('Month', (('january', 'jan'), ('february', 'feb'), ('march', 'mar'), ('april', 'apr'), ('may', 'may'), ('june', 'jun'), ('july', 'jul'), ('august', 'aug'), ('september', 'sep'), ('october', 'oct'), ('november', 'nov'), ('december', 'dec')))], max_length=100, verbose_name='Период отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(choices=[('Декларация по НДС', 'НДС'), ('Декларация по налогу на прибыль', 'Прибыль'), ('Расчет по страховым взносам', 'Взносы'), ('Персонифицированные сведения', 'Персонифицированные'), ('Уведомление об исчисленных суммах налогов', 'Уведомление')], max_length=100, verbose_name='Название отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=100, verbose_name='Год отчета'),
        ),
    ]
