# Generated by Django 4.2.2 on 2023-07-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_alter_report_period_alter_report_report_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Срок сдачи'),
        ),
    ]
