# Generated by Django 4.2.2 on 2023-07-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_report_deadline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='deadline_status',
            field=models.BooleanField(default=False),
        ),
    ]
